services:
  db:
    image: postgres:16
    container_name: gf_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC
      PGTZ: UTC
      # POSTGRES_INITDB_ARGS: "--timezone=UTC"
    command: postgres -c timezone=UTC -c log_timezone=UTC

volumes:
  db_data:
