spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/getnet_facturante?timezone=UTC&stringtype=unspecified
    username: gf_user
    password: 
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionInitSql: SET TIME ZONE 'UTC';
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: UTC
  jvm:
    timezone: UTC

server:
  port: 1234

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  cors:
    allowed-origins: http://localhost:5173

jwt:
  # Generar secretos base64 de al menos 256 bits. Nunca commitear reales.
  access:
    secret: "dGhpc19pc19hX3Rlc3RfYWNjZXNzX3NlY3JldF9iYXNlNjQ="
    ttl-seconds: 900
  refresh:
    secret: "dGhpc19pc19hX3Rlc3RfcmVmcmVzaF9zZWNyZXRfYmFzZTY0"
    ttl-seconds: 604800
  issuer: "gf-connector"
  audience: "getnet-facturante"
  
# Configuración de seguridad adicional
security:
  cors:
    allowed-origins: ${app.cors.allowed-origins:http://localhost:5173}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  rate-limit:
    enabled: true
    requests-per-minute: 60

logging:
  level:
    com.gf: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

# Configuración de GetNet - Los valores reales están en application-local.properties
getnet:
  api-key: 
  api-secret: 
  seller-id: 
  environment: sandbox # sandbox, pre, production
  
  # Credenciales de webhook (opcional)
  webhook:
    username: 
    password: 

# Configuración de Facturante - Los valores reales están en application-local.properties
facturante:
  service-url: 
  empresa: 
  usuario: 
  password: 
  prefijo: 00001
  tipo-comprobante: FB

# Configuración de notificaciones por email
notification:
  email:
    enabled: true
    admin-email: admin@getnet-facturante.com
    from: noreply@getnet-facturante.com
    smtp:
      host: smtp.gmail.com
      port: 587
      username: 
      password: 
      auth: true
      starttls: true

# Configuración de reconciliación
reconciliation:
  enabled: true
  days-to-check: 7
  cron:
    daily: "0 0 2 * * ?"
    weekly: "0 0 3 * * SUN"
    cleanup: "0 0 4 1 * ?"

# Configuración de backup automático
backup:
  enabled: true
  directory: ./backups
  retention-days: 30
  cron:
    daily: "0 0 1 * * ?"
    weekly: "0 30 0 * * SUN"